### ISSUE TITLE
Tool/Option to help identify OffTargetRegions

### ISSUE THREAD

**Issue by monkollek** [Illumina/ExpansionHunter#1]
Hi!

I would like to use this tool for things other than the 3 examples. Currently to do this, the user needs to create a specs json file that includes OffTargetRegions. 

Are there any plans to offer a tool/option such that users can explore potential off target regions similar to Supplementary Figure 4? (http://biorxiv.org/content/early/2016/12/19/093831)

Or alternatively, creating a file for all the known repeat expansion genes such as those reported in https://www.ncbi.nlm.nih.gov/pubmed/17417937.

At the moment, Supplementary Section 3.2 is all the user has for guidance if they would like to explore a different loci.

Thanks!

Regards,
Monkol

**Comment by egor-dolzhenko** [comment]
Hi Monkol. Sorry for the late reply. For some reason I did not get an email about the open issue.

We are aiming to release the tools for annotating repeats together with a catalog of spec files later this year (probably in a separate repository). However, a preliminary catalog should be ready in 1-2 weeks. Would you like to try it out? If so, feel free to send me an email (edolzhenko@illumina.com) and I will send you the catalog as soon as it is ready.

Egor

**Comment by monkollek** [comment]
Hi Egor,

Thanks! Would love to give the preliminary catalog a try and give you feedback. Will send an email.
