### ISSUE TITLE
output vcf file

### ISSUE THREAD

**Issue by woodoo46** [Illumina/ExpansionHunter#11]
Hi, ExpansionHunter developers,

I noticed that in the output vcf file, the GT field was labeled as 1, instead of ./., 0/0, 0/1, 1/1. What does this mean?

Thanks.

George

**Comment by egor-dolzhenko** [comment]
Thanks for the question, George.

GT fields with only one allele value correspond to haploid genotypes. Such genotypes could appear on Y or male X. (Note that the new version of Expansion Hunter allows user to specify sex of the input sample.)

Please let me know if I answered your question or if there is anything else that you'd like to know.

Thanks,
Egor

**Comment by woodoo46** [comment]
Thanks for the quick reply! But this is on chr7, which is supposed to be diploid. Here is part of the record
GT:SO:SP:CN:CI  1:FLANKING:6:22:22-22

George
