### ISSUE TITLE
[Invalid contig name chr1]

### ISSUE THREAD

**Issue by rusnlkaterina** [Illumina/ExpansionHunter#110]
Hey,
I have trouble related to the incompatibility of the contigs (for example, chr 1 against 1). 
The trouble goes just after the solved one "Invalid contig name X" which successfully was eliminated.

I've tried all the possible things starting from the changing reference genome (37, 38 to the local test reference.fa) and ending with the usage of my own bam file as an inputs while do tests.
I don't know exactly where I am wrong.

**Comment by egor-dolzhenko** [comment]
Hi @rusnlkaterina. Since you already closed this issue, I am assuming you were able to resolve the problem, right? If not, please let me know if I can do anything to help.

**Comment by rusnlkaterina** [comment]
Unfortunately, nope,
I just have no idea how to explain it explicitly cause I have not provided any script there..

**Comment by rusnlkaterina** [comment]
I have trouble reproducing the bug, so, it would be better if I close the issue cause it is not related to ExpansionHunter's execution. 
Thank you for your concern.

**Comment by egor-dolzhenko** [comment]
@rusnlkaterina This sounds good. Please feel free to reopen the issue if needed
