### ISSUE TITLE
Realigned BAM visualization

### ISSUE THREAD

**Issue by apredeus** [Illumina/ExpansionHunter#111]
Hello, 

I was trying to visualize the realigned reads, but it seems like the format is off somehow - IGV is not able to visualize the reads. I can't seem to spot why. Any suggestions? 

Thank you in advance!

**Comment by egor-dolzhenko** [comment]
Hi Alex,

Yes, unfortunately IGV won't be able to visualize graph-realigned reads. We have a special tool for this: https://github.com/Illumina/GraphAlignmentViewer/

Note that we are planning to release a new visualizer for ExpansionHunter in a few weeks.

I hope this helps. If you have any feedback on the visualization tool or ExpansionHunter itself please us know.
Egor

**Comment by apredeus** [comment]
Thank you! I've obtained a strange result and I'm not sure how to interpret it. I get heterozygous 43 unit repeat identified at PHOX2B (it's a MGI 60x PCR-free genome). Visualization looks like this. Does this look like an artifact? Thank you in advance!

![image](https://user-images.githubusercontent.com/7825825/101042528-34e80a00-3575-11eb-9d38-47af62cfc4c4.png)

**Comment by egor-dolzhenko** [comment]
Thanks for sharing the plot! Yes, this looks like a data artifact since reads supporting the 43 unit repeat are of low quality. (Note that our software is designed for and tested on Illumina PCR-free WGS.)
