### ISSUE TITLE
Removed repeats NIPA1, GLS and RFC1

### ISSUE THREAD

**Issue by leonschuetz** [Illumina/ExpansionHunter#113]
Hello,

I'm currently updating from v3 to v4 and found out that the repeats NIPA1, GLS and RFC1 are missing in the variant catalog of the new release. Why got they removed? 

Best regards,
Leon

**Comment by egor-dolzhenko** [comment]
Hi Leon,

Apologies, this was an oversight on our end. We will add these repeats back in 4.0.2 release. Meanwhile, please feel free to use the v3 catalog.

Best wishes,
Egor

**Comment by leonschuetz** [comment]
Ok, no problem. 
Then I will use the old catalog until it is fixed.

Best regards,
Leon

**Comment by egor-dolzhenko** [comment]
@leonschuetz, FYI the repeats are now included in [the latest release](https://github.com/Illumina/ExpansionHunter/releases/tag/v4.0.2).
