### ISSUE TITLE
`analyzers.size() == 1'

### ISSUE THREAD

**Issue by mvcakir** [Illumina/ExpansionHunter#118]
Hello,

I'm having an issue like I paste below:

"ExpansionHunter: /opt/conda/conda-bld/expansionhunter_1602022417547/work/sample_analysis/HtsSeekingSampleAnalysis.cpp:186: void ehunter::{anonymous}::analyzeReadPair(ehunter::AnalyzerFinder&, const ehunter::Read&, const ehunter::Read&, const AlignmentStatsCatalog&): Assertion `analyzers.size() == 1' failed.
ExpansionHunter --reads sample.bam --hg38.fa --variant-catalog EH.json --output-prefix EH_out/sample"

The strange thing is it happens at a certain entry in the json file:

"
{
    "ReferenceRegion": "chr7:87547571-87547601", 
    "VariantType": "RareRepeat", 
    "LocusStructure": "(AAAGGAAGGGAAGGGAAGGG)*", 
    "LocusId": "ABCB1_38", 
    "OfftargetRegions": [
      "chr20:18695680-18695731", 
      "chr4:137894908-137895913", 
      "chr3:132044263-132045046", 
      "chr7:87547667-87547860"
    ]
  }, 
"

I'm not quite sure about this error and I couldn't find anything about it.

Thanks a lot

Volkan

**Comment by egor-dolzhenko** [comment]
Hello Volkan,

Thank you for reporting this issue! I believe the offtarget region "chr7:87547667-87547860" is the source of the error. Could you please try removing it?

When ExpansionHunter analyzes this repeat, it extends both sides of the "ReferenceRegion" by 1kb, which causes it to overlap the offtarget region above (making it superfluous). We will update the program to generate a meaningful error message that superfluous offtarget regions are not allowed.

Best wishes,
Egor

**Comment by mvcakir** [comment]
Dear Egor,

Thank you very much for the very quick response. The problem was exactly what you pointed out, it works without that problematic offtarget region. Thanks a lot.

Best,

Volkan

**Comment by egor-dolzhenko** [comment]
Glad to hear it, Volkan! Please let me know if you run into any other issues.
