### ISSUE TITLE
output vcf file

### ISSUE THREAD

**Issue by woodoo46** [Illumina/ExpansionHunter#12]
Sorry, I accidentally closed the issue. The region we look at is on chr7, which is supposed to be diploid. Here is part of the record

GT:SO:SP:CN:CI 1:FLANKING:6:22:22-22

Thanks.

George

**Comment by egor-dolzhenko** [comment]
Sounds good. Which version of Expansion Hunter are you running?

**Comment by egor-dolzhenko** [comment]
I can offer a general explanation even without knowing the exact version number. It appears that this VCF line was produced by an earlier version of Expansion Hunter that did not have an STR genotyper built-in (and would output as many repeat alleles as were detected). In this particular case, Expansion Hunter detected only flanking reads (reads that start at one of the flanks of the repeat and end inside the repeat) and reported one allele of size 22 repeat units. This could be an indication that the repeat is poorly covered by the reads. The latest version of the program will produce a diploid genotype.

Marking the issue as resolved for now. Please feel free to reopen if needed.
