### ISSUE TITLE
Request to add GIPC1 (Deng J, Yu J, Li P, et al.  2020)

### ISSUE THREAD

**Issue by fjmuzengyiheng** [Illumina/ExpansionHunter#128]
Hi, expansion of GGC repeat in GIPC1 was found to be associated with Oculopharyngodistal Myopathy 2 (OPDM2).
GGC repeat located in 5UTR of GIPC1 with simple form. Could you please kindly add GIPC1 into json file? Thank you!

**Comment by eberle** [comment]
Thanks for using ExpansionHunter. I was able to identify hg19 coordinates of the repeat and after the weekend we can confirm the performance of this repeat and update the json files to include this repeat.

**Comment by fjmuzengyiheng** [comment]
> Thanks for using ExpansionHunter. I was able to identify hg19 coordinates of the repeat and after the weekend we can confirm the performance of this repeat and update the json files to include this repeat.

Thank you. That is nice of you!

**Comment by yjqiu** [comment]
Hi @fjmuzengyiheng I have tested the annotation from Stranger provided by @dnil and merged it into master branch. You can check it there.

**Comment by fjmuzengyiheng** [comment]
> Hi @fjmuzengyiheng I have tested the annotation from Stranger provided by @dnil and merged it into master branch. You can check it there.

thank you. it is nice of you  : }
