### ISSUE TITLE
Questions about how to set '--output prefix' 

### ISSUE THREAD

**Issue by sunbacteria** [Illumina/ExpansionHunter#132]
Hi!
I want to use ExpansionHunter to find specific STRs in our bam files. However, I am not familiar with the codes.

I noticed that in the given example, it writes:'--output-prefix output/repeats'
In my own script, i change it to '--output-prefix <mypath to save the output files and the target filename>'
I am not sure if I make it right. After I tried to run this script, it comes out that '--output-prefix' is required but missing and there is also an error report that "--output-prefix: command not found".

I wondered where i got it wrong.

Thanks!
<img width="594" alt="my codes" src="https://user-images.githubusercontent.com/86388982/123187372-9ef1dd80-d4cc-11eb-8028-b2974e359617.png">

**Comment by egor-dolzhenko** [comment]
Apologies for the late reply! Could you please confirm that there are no spaces after the `\` character on the second line from the bottom? If there is a space, `\` would not escape the end of the line and your shell will interpret `--output-prefix` as a separate command (which will lead to "--output-prefix: command not found" error).

**Comment by GabevandenHoeven** [comment]
Hello!

I am trying to do the same thing and I am running into a similar problem.
The only thing that is different is that with me it says: [the option '--output-prefix' is required but missing].
I also don't know what the issue could be, though I can confirm that there is no space after the "\" in my code.

Thanks!

**Comment by egor-dolzhenko** [comment]
Thanks for the question! Could you please copy/paste the exact command you are using?

**Comment by GabevandenHoeven** [comment]
Hello, thanks for your quick reply!
As I was writing this someone noticed that one of the dashes was a windows character. This turned out to be the issue for me.

**Comment by egor-dolzhenko** [comment]
Glad to hear that you were able to resolve the issue!
