### ISSUE TITLE
Error in installation (make command)

### ISSUE THREAD

**Issue by tahirasma** [Illumina/ExpansionHunter#134]
Greetings!

I am trying to install ExpansionHunter but I encounter error as below (while scanning dependencies of genotyping)

The version of boost is 1.76.0

Scanning dependencies of target genotyping
[ 38%] Building CXX object genotyping/CMakeFiles/genotyping.dir/AlignMatrix.cpp.o
[ 39%] Building CXX object genotyping/CMakeFiles/genotyping.dir/AlleleChecker.cpp.o
[ 39%] Building CXX object genotyping/CMakeFiles/genotyping.dir/RepeatGenotype.cpp.o
In file included from /home/asma/Documents/ExpansionHunter/ExpansionHunter/genotyping/RepeatGenotype.cpp:23:
/home/asma/Documents/ExpansionHunter/ExpansionHunter/genotyping/RepeatGenotype.hh: In member function ‘ehunter::NumericInterval ehunter::RepeatGenotype::shortAlleleSizeInUnitsCi() const’:
/home/asma/Documents/ExpansionHunter/ExpansionHunter/genotyping/RepeatGenotype.hh:65:80: error: implicitly-declared ‘constexpr ehunter::NumericInterval::NumericInterval(const ehunter::NumericInterval&)’ is deprecated [-Werror=deprecated-copy]
   65 |     NumericInterval shortAlleleSizeInUnitsCi() const { return alleles_.front().ci; }
      |                                                                                ^~
In file included from /home/asma/Documents/ExpansionHunter/ExpansionHunter/genotyping/RepeatGenotype.hh:32,
                 from /home/asma/Documents/ExpansionHunter/ExpansionHunter/genotyping/RepeatGenotype.cpp:23:
/home/asma/Documents/ExpansionHunter/ExpansionHunter/common/Common.hh:82:22: note: because ‘ehunter::NumericInterval’ has user-provided ‘ehunter::NumericInterval& ehunter::NumericInterval::operator=(const ehunter::NumericInterval&)’
   82 |     NumericInterval& operator=(const NumericInterval& other)
      |                      ^~~~~~~~
In file included from /home/asma/Documents/ExpansionHunter/ExpansionHunter/genotyping/RepeatGenotype.cpp:23:
/home/asma/Documents/ExpansionHunter/ExpansionHunter/genotyping/RepeatGenotype.hh: In member function ‘ehunter::NumericInterval ehunter::RepeatGenotype::longAlleleSizeInUnitsCi() const’:
/home/asma/Documents/ExpansionHunter/ExpansionHunter/genotyping/RepeatGenotype.hh:84:78: error: implicitly-declared ‘constexpr ehunter::NumericInterval::NumericInterval(const ehunter::NumericInterval&)’ is deprecated [-Werror=deprecated-copy]
   84 |     NumericInterval longAlleleSizeInUnitsCi() const { return alleles_.back().ci; }
      |                                                                              ^~
In file included from /home/asma/Documents/ExpansionHunter/ExpansionHunter/genotyping/RepeatGenotype.hh:32,
                 from /home/asma/Documents/ExpansionHunter/ExpansionHunter/genotyping/RepeatGenotype.cpp:23:
/home/asma/Documents/ExpansionHunter/ExpansionHunter/common/Common.hh:82:22: note: because ‘ehunter::NumericInterval’ has user-provided ‘ehunter::NumericInterval& ehunter::NumericInterval::operator=(const ehunter::NumericInterval&)’
   82 |     NumericInterval& operator=(const NumericInterval& other)
      |                      ^~~~~~~~
/home/asma/Documents/ExpansionHunter/ExpansionHunter/genotyping/RepeatGenotype.cpp: In function ‘std::ostream& ehunter::operator<<(std::ostream&, const ehunter::RepeatGenotype&)’:
/home/asma/Documents/ExpansionHunter/ExpansionHunter/genotyping/RepeatGenotype.cpp:65:12: error: implicitly-declared ‘constexpr ehunter::NumericInterval::NumericInterval(const ehunter::NumericInterval&)’ is deprecated [-Werror=deprecated-copy]
   65 |     out << shortAlleleCi;
      |            ^~~~~~~~~~~~~
In file included from /home/asma/Documents/ExpansionHunter/ExpansionHunter/genotyping/RepeatGenotype.hh:32,
                 from /home/asma/Documents/ExpansionHunter/ExpansionHunter/genotyping/RepeatGenotype.cpp:23:
/home/asma/Documents/ExpansionHunter/ExpansionHunter/common/Common.hh:82:22: note: because ‘ehunter::NumericInterval’ has user-provided ‘ehunter::NumericInterval& ehunter::NumericInterval::operator=(const ehunter::NumericInterval&)’
   82 |     NumericInterval& operator=(const NumericInterval& other)
      |                      ^~~~~~~~
/home/asma/Documents/ExpansionHunter/ExpansionHunter/common/Common.hh:123:61: note:   initializing argument 2 of ‘std::ostream& ehunter::operator<<(std::ostream&, ehunter::NumericInterval)’
  123 | std::ostream& operator<<(std::ostream& out, NumericInterval numericInterval);
      |                                             ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
/home/asma/Documents/ExpansionHunter/ExpansionHunter/genotyping/RepeatGenotype.cpp:71:23: error: implicitly-declared ‘constexpr ehunter::NumericInterval::NumericInterval(const ehunter::NumericInterval&)’ is deprecated [-Werror=deprecated-copy]
   71 |         out << "/" << longAlleleCi;
      |                       ^~~~~~~~~~~~
In file included from /home/asma/Documents/ExpansionHunter/ExpansionHunter/genotyping/RepeatGenotype.hh:32,
                 from /home/asma/Documents/ExpansionHunter/ExpansionHunter/genotyping/RepeatGenotype.cpp:23:
/home/asma/Documents/ExpansionHunter/ExpansionHunter/common/Common.hh:82:22: note: because ‘ehunter::NumericInterval’ has user-provided ‘ehunter::NumericInterval& ehunter::NumericInterval::operator=(const ehunter::NumericInterval&)’
   82 |     NumericInterval& operator=(const NumericInterval& other)
      |                      ^~~~~~~~
/home/asma/Documents/ExpansionHunter/ExpansionHunter/common/Common.hh:123:61: note:   initializing argument 2 of ‘std::ostream& ehunter::operator<<(std::ostream&, ehunter::NumericInterval)’
  123 | std::ostream& operator<<(std::ostream& out, NumericInterval numericInterval);
      |                                             ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [genotyping/CMakeFiles/genotyping.dir/build.make:89: genotyping/CMakeFiles/genotyping.dir/RepeatGenotype.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:967: genotyping/CMakeFiles/genotyping.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

Looking forward for your response.

Regards,

**Comment by egor-dolzhenko** [comment]
Thank you for reporting the issue. What operating system are you using and what version of the C++ compiler do you have?

Also, could you please check if one of the provided binaries works on your system? The links to the binaries are located on the [release](https://github.com/Illumina/ExpansionHunter/releases/tag/v4.0.2) page under "Assets".

**Comment by tahirasma** [comment]
Thanks for your reply.

OS: Ubuntu 20
Boost: 1.76.0

But I downloaded the binaries and it worked perfectly fine. Thanks again
