### ISSUE TITLE
Using different input bam files 

### ISSUE THREAD

**Issue by MeiShu00** [Illumina/ExpansionHunter#139]
Hi, 

I understand that BAM or a CRAM file with alignments of reads from a PCR-free WGS sample is one of the required inputs. 

Hence, would like to ask the following questions:
1. Will ExpansionHunter work with PCR-amplified targeted STR?
2. Why are reads from a PCR-free WGS sample required? 

Thanks !

**Comment by egor-dolzhenko** [comment]
Thanks for the questions!

ExpansionHunter (EH) assumes that sequencing coverage is relatively uniform throughout the repeat region (hence the requirement for PCR-free WGS).

EH will run on PCR-amplified data, however, some repeats may not be genotyped correctly. For example, long 100% GC repeats are very difficult to amplify with PCR.

Visualization tools like REViewer can help to visually investigate sequencing data in repeat regions of interest: https://github.com/Illumina/REViewer

Did I answer your questions? Please let me know if there is anything else you'd like to know.

Best wishes,
Egor

**Comment by MeiShu00** [comment]
Dear Egor, 

Yes, my questions are answered ! Thank you !
