### ISSUE TITLE
can expansionhunter accepts bam from pacbio long-read sequencing?

### ISSUE THREAD

**Issue by WeiCSong** [Illumina/ExpansionHunter#195]
Hi, given that expansionhunter has good performance on NGS data, and that long-read data could largely improve TR calling, i'm wondering whether they can be combined and use expansionhunter to analyze long-read data. Thanks!

**Comment by andreasssh** [comment]
No, but for PacBio you can use [https://github.com/PacificBiosciences/trgt](https://github.com/PacificBiosciences/trgt) which is at least as great as EH.

**Comment by WeiCSong** [comment]
thanks for the information!
