### ISSUE TITLE
Related to output (bam file)

### ISSUE THREAD

**Issue by jawad9-11** [Illumina/ExpansionHunter#201]
I wanted to ask that we are getting output in three formats like bam, json and vcf files. Is there anyway we can specify the output format as the bam files are taking a lot of storage.
Thank You!

**Comment by andreasssh** [comment]
AFAIK this is not available by default, but I added the feature to disable BAM output into my EH fork. See the new v5.0.0+2 at [https://gitlab.com/andreassh/ExpansionHunter](https://gitlab.com/andreassh/ExpansionHunter) @jawad9-11

**Comment by jawad9-11** [comment]
ok, noted. thank you!
