### ISSUE TITLE
Assertion `!frag[0].name.empty() && !frag[1].name.empty()' failed

### ISSUE THREAD

**Issue by nh13** [Illumina/ExpansionHunter#32]
Options:

```
--sex female --min-score -0.1 --min-baseq 20 --min-anchor-mapq 0 --region-extension-length 10000 --read-depth 30
```

<detail>
<summary>Assertion produced by ExpansionHunter</summary>

```
ExpansionHunter: src/irr_counting.cc:332: int CountAlignedIrr(const BamFile&, const Parameters&, const AlignPairs&, std::map<std::basic_string<char>, int>&, const std::vector<std::vector<std::basic_string<char> > >&, std::vector<RepeatAlign>*): Assertion `!frag[0].name.empty() && !frag[1].name.empty()' failed.
```
</detail>

**Comment by egor-dolzhenko** [comment]
Thank you for reporting the issue. It looks like the program is having difficulty with extracting alignments from the input BAM. Could you please describe what kind of data you are working with and how it was aligned?

Also, might it be possible to get a piece of a BAM file with reads around the repeat region? I would be happy to send you a script that extracts the relevant reads.

**Comment by nh13** [comment]
Is there an email I can send you the subsetted BAM?

**Comment by egor-dolzhenko** [comment]
Sure, it is edolzhenko@illumina.com. Thank you!

**Comment by egor-dolzhenko** [comment]
I see. Thank you for noticing this. I will change the program to throw an error if the user enters a value outside of the reasonable range.
