### ISSUE TITLE
Recommendations for setting --min-score when the repeat is inexact

### ISSUE THREAD

**Issue by nh13** [Illumina/ExpansionHunter#33]
For many larger repeats, the same repeat unit isn't repeated exactly many times.  Besides a few base differences, there are also length differences (one or two more or fewer bases).  For just mismatches, I would assume setting `--min-score` to some reasonable value based on _how_ different the sequences are makes sense (I'd like advice on how to determine this value)*.  I am also wondering if ExpansionHunter will handle length differences?   I will send you the repeat via email (egor-dolzhenko).

* I could align the known repeat units in that large VNTR to determine a similarity score similar to the weighted score ExpansionHunter uses.

**Comment by egor-dolzhenko** [comment]
VNTRs with larger repeat unit is something that we currently work towards. However, at the moment ExpansionHunter cannot handle such repeats well. The current version of the program is designed for short tandem repeats (and their expansions) and the repeat unit is assumed to be highly conserved: mismatches are allowed but indels are not allowed. The default value of `min-score` cutoff should be reasonable for the types of repeats that the program can genotype well.

An upcoming major update to ExpansionHunter will allow a lot more flexibility in the repeat unit and so should be able to handle larger VNTRs. Once these changes are implemented, the strategy you proposed for determining the similarity score cutoff should work very well.

I will keep the issue open until the next major update.

**Comment by nh13** [comment]
@egor-dolzhenko I would be glad to assist in testing whatever alpha/beta version you have.  I'll reply with more details via email.  Thank-you for the update on your progress.  It is very exciting!

**Comment by egor-dolzhenko** [comment]
Thanks, @nh13! This sounds wonderful. Most of the core components of the new version are already implemented (I will be happy to provide the details by email if you are interested). So I could soon send you a version of the program that will reveal if the new changes will enable accurate genotyping of VNTRs you are interested in.

**Comment by AlfredoKCL** [comment]
Hello all,

Has the new version been implemented and released yet?

Cheers

**Comment by egor-dolzhenko** [comment]
We have just [pre released](https://github.com/Illumina/ExpansionHunter/releases/tag/v3.0.0-rc1) a new version of the program. It is **a lot** more flexible than the previous versions, though we are still working on tests that will delineate how much imperfections in the repeat unit it could tolerate before performance degrades.

Are you interested in any specific repeats? If yes, I would be grateful if you could share some information about their location and structure. If you prefer, please feel free to reach out by email (edolzhenko@illumina.com).

Best wishes,
Egor

**Comment by amrita1983** [comment]
Hi, 
I am interested in CGG repeat fro FMR1 gene, can please help me on that.
