### ISSUE TITLE
PCR-free WGS? Illumina SeqLab specific TruSeq Nano High Throughput library?

### ISSUE THREAD

**Issue by CKoriath** [Illumina/ExpansionHunter#36]
Hello Egor,
this is a really interesting project. I'm trying to work out whether we can apply it to our data. I noticed that in your methods you state that some of the samples were prepared using Illumina SeqLab specific TruSeq Nano High Throughput library kits, which is what was used in our WGS, in combination with Illumina HiSeqX sequencing. What was your experience with the samples prepared using Illumina SeqLab specific TruSeq Nano High Throughput libraries? Did your method work despite the inital PCR step?
Thank you!

**Comment by egor-dolzhenko** [comment]
Thank you for considering to use the program! In my experience repeat expansions with lower GC content (like CAG repeats) can be called from Nano data. However, one should perform some quality control analyses before running the program to make sure that target repeats are represented in the data reasonably well.

If you don't mind providing a brief description of your dataset and what kinds of analyses you are looking to do, I will be able to give better advice. For example, it would be useful to know how many samples you have and are you looking into known pathogenic repeats or trying to discover new ones. Please feel free to email me directly (edolzhenko@illumina.com).

Best wishes,
Egor

**Comment by YiweiNiu** [comment]
Hi Egor,

> However, one should perform some quality control analyses before running the program to make sure that target repeats are represented in the data reasonably well.

Could you please explan this more? I'd like to know how to perform quality control on pcr-not-free samples.

Bests,
Yiwei Niu

**Comment by egor-dolzhenko** [comment]
Yiwei, a quick-and-dirty way to start would be to look at a 2Kb region around the FMR1 repeat (hg19: chrX:146993568-146993628, hg38: chrX:147912050-147912110) in IGV in a few of your samples.

This 100% GC repeat is often pretty long even in healthy people. So if there is a severe PCR-related coverage issue in your data, there is a good chance that you will notice it in this locus: There will be a visible drop in reads immediately around the repeat.

If it is permissible, feel free to email me the IGV screenshots. I could help you to interpret them.

**Comment by YiweiNiu** [comment]
Thank you very much. I would check several samples in IGV.
