### ISSUE TITLE
Lots of Alleles

### ISSUE THREAD

**Issue by charliecurnin** [Illumina/ExpansionHunter#37]
Hi guys, 

I'm trying to understand the VCF output of ExpansionHunter, and I have some questions. I'm profiling the (autosomal) Huntington repeat, and I'm seeing several alleles, when I would expect just two. 

For example, 
```
$ grep -i htt *.vcf
proband.vcf:4 3076603 HTT     CCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAG      <STR20>,<STR80> .       PASS    SVTYPE=STR;END=3076660;REF=19;RL=57;RU=CAG      GT:SO:SP:CN:CI       0/1/2:SPANNING/SPANNING/INREPEAT:2/11/14:19/20/80:././65-93
parentA.vcf:4 3076603 HTT     CCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAG      <STR16>,<STR17>,<STR20> .       PASS    SVTYPE=STR;END=3076660;REF=19;RL=57;RU=CAG  GT:SO:SP:CN:CI   0/1/2/3:SPANNING/SPANNING/SPANNING/SPANNING:3/1/10/12:19/16/17/20:./././.
control.vcf:4 3076603 HTT     CCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAG      <STR17>,<STR20>,<STR22>,<STR23> .       PASS    SVTYPE=STR;END=3076660;REF=19;RL=57;RU=CAG   GT:SO:SP:CN:CI  1/2/3/4:SPANNING/SPANNING/SPANNING/SPANNING:12/1/2/5:17/20/22/23:./././. 
```

Is ExpansionHunter really trying to say that the proband has three alleles (`0/1/2`) —and parentA and the control have four? Am I misinterpreting this? 

`<STR20>` (in the proband) seems pretty close to the reference of 19 repeats. Are they in fact same and `0/1/2` really should be `0/2` (i.e., one haplotype with the normal 19 repeats, and the other with 80?)

Specific context: The proband seems to 80 have repeats—which would fall into the disease-causing range—which fits. But does the parent have an expansion too?

**Comment by egor-dolzhenko** [comment]
Thank you for the question!

It looks like the VCFs were produced by an early version of the program. This version did minimal filtering of read alignments and would record all candidate haplotypes in a VCF file.

Would it be possible to run the latest version of the program on these samples? If this is not an option, would you be able to share the output files containing read alignments (*.log)? They would help to interpret this call.

**Comment by egor-dolzhenko** [comment]
Closing this for now. Please feel free to reopen if needed.
