### ISSUE TITLE
Mean argument is 0

### ISSUE THREAD

**Issue by mattdmem** [Illumina/ExpansionHunter#42]
Hello,

version: v3.0.0-rc1-linux_x86_64

I get this error when trying to run ExpansionHunter. Illumina HiSeq 2000 WGS data.

`2019-01-16T08:59:49,[Error in function boost::math::poisson_distribution<d>::poisson_distribution: Mean argument is 0, but must be > 0 !]
`
Any Ideas?

Thanks
Matt

**Comment by egor-dolzhenko** [comment]
Hi Matt,

I am sorry about the error. We have just encountered and fixed it on our end. We will push the fix in rc2 release by early next week or sooner.

Best wishes,
Egor

**Comment by mattdmem** [comment]
Great thanks!
