### ISSUE TITLE
Is reported ATNX2 repeat unit correct?

### ISSUE THREAD

**Issue by melnel000** [Illumina/ExpansionHunter#44]
I have noted that the repeat unit reported for ATXN2 in the output json file is GCT. Is this correct? Since in the literature I see it is referred to as a CAG repeat.

**Comment by egor-dolzhenko** [comment]
Thanks for the question! The input and output files produced by the program specify the repeat unit in the reference orientation. This representation could differ from what is reported in the literature by reverse complement (and shifts).

In this particular case, `GCTGCTGCTGCT` repeat is `AGCAGCAGCAGC` repeat on the opposite strand which is a CAG repeat.

Does this answer your question?

Best wishes,
Egor

**Comment by melnel000** [comment]
Thanks Egor- your explanation is perfectly clear.

Kind regards,
Melissa

**Comment by egor-dolzhenko** [comment]
Glad to hear it, Melissa. I will close this issue, but if you have any further questions about how to interpret the output or suggestions on what we could improve please reach out anytime either directly by email or through github.

Best wishes,
Egor
