### ISSUE TITLE
bad_alloc for early regions

### ISSUE THREAD

**Issue by christopher-schroeder** [Illumina/ExpansionHunter#46]
I retrieve a bad_alloc after about 20 minutes when the definition includes at least one region with very small start/stop values, for example

 {
  "LocusId": "test",
  "LocusStructure": "(TAACCC)*",
  "ReferenceRegion": "chr1:9999-10500",
  "VariantType": "Repeat"
 }
]

The magic number seems to be 10991 or less and the error seems to occure when parsing the cataloge json, since the repeat detection step doesn't even start.

Edit: Sorry 10991 is still working, but take MUCH longer to parse than higher regions. 9999 definitely fails.

**Comment by egor-dolzhenko** [comment]
I am sorry about the error.

It looks like this repeat is flanked by `N`s in the reference genome. The program tries to replace these Ns with all possible combinations of A, T, C, G and eventually runs out of memory.

The next version of the program will produce a meaningful error message when it encounters a situation like this. I will also add a section to the manual that explains what to look for when defining new repeat regions (in particular that the sequence surrounding the repeat region must be known).

We have another (not yet released) program that would be more appropriate for repeats like above. If you are interested to test it out, please feel free to reach out anytime (edolzhenko@illumina.com).

-Egor

**Comment by christopher-schroeder** [comment]
Thank you. I have removed all regions containing N in the +- 1000bp flanking sequences. Now the json is read without problems.

**Comment by egor-dolzhenko** [comment]
Great! The [v3.0.0-rc4](https://github.com/Illumina/ExpansionHunter/releases/tag/v3.0.0-rc4) release addresses this issue by producing an informative error message when flanking sequence contains 5 or more Ns.

If we ever encounter an important repeat that is surrounded by Ns (or any other unreliable sequence) in the reference we will implement a way to define custom flanks.
