### ISSUE TITLE
Repeat Expansion for Mutation in FMR1 gene

### ISSUE THREAD

**Issue by amrita1983** [Illumina/ExpansionHunter#51]
Hi,

I am trying to find out repeat expansion of a affected patient for FMR1 genes, but no sure whether the bam file aligned using the hg19 reference is sufficient enough because it was unable to capture the repeat count using that bam, is there any specific command or modification is there that can help me to get that.

**Comment by dnil** [comment]
FMR1 from hg19 works well for us! Were any errors encountered? 

If you specify a command and error message I'm sure it is easier to figure out what went wrong.
Just checking: did you index your bam file (using e.g. `samtools index patient.bam`) and place the index (bai) file in the same folder as the bam file?

**Comment by amrita1983** [comment]
Hi,

I am using this command

/home/ngs/Downloads/ExpansionHunter-v3.0.0-rc2-linux_x86_64/bin/ExpansionHunter --reads /home/ngs/Downloads/RepeatHMM/bin/Prajwal_Wagh_aligned.sorted.bam --reference /mnt/NGS/Human_Exome_hg19/hg19.fa --variant-catalog /home/ngs/Downloads/ExpansionHunter-v3.0.0-rc2-linux_x86_64/variant_catalog/variant_catalog_hg19.json --output-prefix PW_new_TRD --sex male
but the problem is vcf is not showing anything for FMR1 other tools are showing normal count, the patient is an affected one, I don't think its a correct count, is there any probability that when we are aligning this repeat samples to normal genome is missing some of the reads due to read length issue or because when I am seeing the 5' UTR region in bam with IGV number of reads are very less.

**Comment by amrita1983** [comment]
Is there any alignment tool or reference specifically for Triplet repeats like this.

**Comment by egor-dolzhenko** [comment]
Unfortunately it sounds like your data might contain very few or no reads overlapping the FMR1 repeat. This often happens with the FMR1 repeat and other 100% GC repeats in non PCR-free data.

Could you please describe your data (library prep, read length, sequencing instrument)?

**Comment by egor-dolzhenko** [comment]
Closing for now. Please feel free to reopen if this is still an issue.
