### ISSUE TITLE
Is it possible to identify potential disease-associated STR loci genome-wide using ExpansionHunter?

### ISSUE THREAD

**Issue by YiweiNiu** [Illumina/ExpansionHunter#61]
Hi,

I got about 200 WGS samples from a neurogenetic diseases and 200 control samples. I want to use ExpansionHunter to test whether this disease is associated with specific STR loci.

I know ExpansionHunter use a pre-defined loci as reference, but I wonder if it is possible to use it genome-wide. Say using the [simple repeat track](http://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/simpleRepeat.txt.gz) from UCSC. If yes, could you give me some advice about transforming the track into the format that ExpansionHunter needs?

I really appreciate any help you can provide.

Bests,
Yiwei Niu

**Comment by egor-dolzhenko** [comment]
Hi Yiwei,

This is a very nice dataset!

We have been working on a genome-wide catalog of tandem repeats for a while. If everything goes well, we will release it publicly in the near-future. Unfortunately, the repeats from the UCSC simple repeat track contain some really complex regions that are not appropriate to use as-is.

However, we are also getting ready to release software for the detection of novel expansions genome-wide that does not need a pre-defined repeat catalog. Although it has some limitations, it might be a perfect match for your project.

If you don't mind using a pre-release (unpolished) version of the software, I could share it with you. If this sounds good, just send me an email (edolzhenko@illumina.com).

Best wishes,
Egor

**Comment by YiweiNiu** [comment]
Hi Egor,

Thank you for your inputs and patience.

Glad to know that you have a new software! I am very happy to try it on our dataset.

I've sent your an email (from: niuyiwei16@mails.ucas.ac.cn). Please check your mail box.

Best wishes,
Yiwei Niu
