### ISSUE TITLE
Request to add custom variant catalogue for NIPA1

### ISSUE THREAD

**Issue by melnel000** [Illumina/ExpansionHunter#64]
I am interested in analysing the NIPA1 locus in WGS data using ExpansionHunter (publication reference: Tazelaar et al., 2019. Association of NIPA1 repeat expansions with amyotrophic lateral sclerosis in a large international cohort.). Are you able to provide assistance with defining a custom catalogue entry to analyse this locus? Thanks, Melissa.

**Comment by egor-dolzhenko** [comment]
Hi Melissa,

Of course! Thank you for pointing out that this repeat is still not in the catalog. I will check with the authors of the paper if they can share the entry for this repeat.

Best wishes,
Egor

**Comment by melnel000** [comment]
Thanks Egor, that would be great.

**Comment by egor-dolzhenko** [comment]
Hi Melissa,

Here is hg19 definition of the NIPA1 repeat, courtesy of @JokevanVugt.

```json
[
    {
        "VariantType": "Repeat",
        "LocusId": "NIPA1",
        "LocusStructure": "(CGC)*",
        "ReferenceRegion": "chr15:23086366-23086390"
    }
]
```

And here is the corresponding hg38 definition.

```
[
    {
        "VariantType": "Repeat",
        "LocusId": "NIPA1",
        "LocusStructure": "(GCG)*",
        "ReferenceRegion": "chr15:22786677-22786701"
    }
]
```

We will add this repeat to the main repeat catalog as soon as we finish running our standard benchmarking suite.
