### ISSUE TITLE
Getting error message

### ISSUE THREAD

**Issue by amrita1983** [Illumina/ExpansionHunter#81]
Hi,
I am trying to look for SCA repeat in my Whole genome data, but while running the tool i am getting this error
"2019-11-11T14:50:27,[size_in_units = 23 is outside of allowed range (0,22)]"

and the program is exiting no output is getting generated.

**Comment by egor-dolzhenko** [comment]
Thank you for reporting the error. Are you using the latest version of the program? If it is not, could you please check if you are getting the error with the [latest release](https://github.com/Illumina/ExpansionHunter/releases/tag/v3.1.2)?

**Comment by amrita1983** [comment]
Thank you for the reply, i worked with my data using the latest version of the tool. I need one more information do you have any list of repeat for each gene that you have used as minimum. I need that for the prediction of repeat expansion comparison.

**Comment by egor-dolzhenko** [comment]
This sounds good. Could you please share the full log of the EH run that produced the error? (The log that contained the entry `"2019-11-11T14:50:27,[size_in_units = 23 is outside of allowed range (0,22)]"`)

And yes, we have a draft repeat catalog that we would be happy to share with you ahead of the public release. Could you please email me about it at edolzhenko@illumina.com?

By the way, we recently released a program that can determine approximate locations of the expanded repeats that might be relevant for your work. It performs a genome-wide analysis without a pre-defined list of repeats: https://github.com/Illumina/ExpansionHunterDenovo

**Comment by egor-dolzhenko** [comment]
I'll close this issue for now since it looks like the latest changes fix the error. Please feel free to reopen.
