### ISSUE TITLE
Request to add PABPN1 to variant catalog

### ISSUE THREAD

**Issue by MichelledeGroot** [Illumina/ExpansionHunter#87]
Hi,

I want to find PABPN1 repeat expansions, but I saw this repeat is not in the variant catalog. Is it possible to get the correct entry for hg19 for this locus?
Thanks in advance!

**Comment by egor-dolzhenko** [comment]
We would be happy to try to add PABPN1 repeat to the variant catalog. @yjqiu, have you looked at this repeat before by any chance?

**Comment by dnil** [comment]
Looking forward to a well tested one, but for what it's worth I currently use:

hg38
```
    {
      "VariantType": "Repeat",
      "LocusId": "PABPN1",
      "LocusStructure": "(GCG)*",
      "ReferenceRegion": "chr14:23321472-23321490"
}
```
hg19:
```
    {
        "VariantType": "Repeat",
        "LocusId": "PABPN1",
        "LocusStructure": "(GCG)*",
        "ReferenceRegion": "chr14:23790681-23790699"
}
```

**Comment by egor-dolzhenko** [comment]
Thank you very much Daniel! We will run your annotation through our quality-control pipeline and report back the results.

**Comment by yjqiu** [comment]
@MichelledeGroot I run the QC and your annotation looks perfect. I am wondering if you want to make a PR to develop branch? Because you contributed the annotation all by yourself. If you don't want to bother, we can also update by ourselves.

**Comment by MichelledeGroot** [comment]
Thanks for the quick answer!
